# RT-Thread building script for component

from building import *

cwd     = GetCurrentDir()
src     = Glob('*.c')
CPPPATH = [cwd]

group = DefineGroup('I2C', src, depend = ['BSP_USING_PDAM'], CPPPATH = CPPPATH)

Return('group')
